version: "3.8"
services:
  postgres:
    image: postgres:13.10
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.local
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env.local
    command:
      [
        "bash",
        "-c",
        "sleep 10 && /usr/local/bin/pgadmin4 && open http://localhost:5050/browser",
      ]
volumes:
  db_data:
