version: "3.8"
services:
  postgres:
    image: postgres:13.8
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.local
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      # TODO: 環境変数を読み込むようにしたい
      PGADMIN_DEFAULT_EMAIL: task-manager-admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: manager-password
      TZ: Asia/Tokyo
    depends_on:
      - postgres
    command:
      [
        "bash",
        "-c",
        "sleep 10 && /usr/local/bin/pgadmin4 && open http://localhost:5050/browser",
      ]
volumes:
  db_data:
